version: "3"
services:
  alertmanager:
    image: bitnami/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - /home/alertmanager/config.yaml:/opt/bitnami/alertmanager/conf/config.yaml

e