global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.qcloudmail.com:465
  smtp_from: email@gpg123.vip
  smtp_auth_username: email@gpg123.vip
  #smtp_auth_identity: email@gpg123.vip
  smtp_auth_password: Gaopuguang2025Y
  smtp_require_tls: false	
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'webhook'
  # 关键配置：子路由
  routes:
    # 这条子路由匹配所有告警，并发送给 webhook 接收器
    - receiver: 'webhook'
      # 这里的 continue: true 意味着：
      # 发送给 webhook 后，继续匹配后续的路由（即不会停止）
      # 如果设为 false，则匹配到 webhook 后，就不会再发给 email 了
      continue: false
receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'https://lazy-dragon-84.webhook.cool'
      - url: 'https://cloud-server.gpg123.vip/api/webhook/alert'
      # 发送恢复通知
        send_resolved: true
  - name: 'email'
    email_configs:
      - to: 2694484453@qq.com
        send_resolved: true 
#inhibit_rules:
#  - source_match:
 #     severity: 'critical'
 #   target_match:
  #    severity: 'warning'
  #  equal: ['alertname', 'dev', 'instance']
