# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
   - "rules/amd-smi-exporter/*.yml"
   - "rules/node-exporter/*.yml"
   - "rules/jaeger-exporter/*.yml"
   - "rules/kube-state-metrics-exporter/*.yml"
   - "rules/caddy-exporter/*.yml"
   - "rules/spring-boot-exporter/*.yml"
   - "rules/coredns-exporter/*.yml"
   - "rules/frps-exporter/*.yml"
   - "rules/traefik-exporter/*.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    metrics_path: '/metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ "localhost:9090" ]
  #servers
  - job_name: "prometheus-servers"
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/prometheus-servers/*.json
  #spring-boot类型
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/spring-boot-exporter/*.json
  #node-exporter类型
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/node-exporter/*.json
  #amd-smi-exporter类型
  - job_name: 'amd-smi-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/amd-smi-exporter/*.json
  #amd-gpu-exporter类型
  - job_name: 'amd-gpu-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/amd-gpu-exporter/*.json
  #nginx-exporter类型
  - job_name: 'nginx-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/nginx-exporter/*.json
  #coredns-exporter类型
  - job_name: 'coredns-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/coredns-exporter/*.json
  #metrics-server-exporter类型
  - job_name: 'metrics-server-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/metrics-server-exporter/*.json
  #caddy类型
  - job_name: 'caddy-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/caddy-exporter/*.json
  #traefik类型
  - job_name: 'traefik-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/traefik-exporter/*.json
  #jaeger类型
  - job_name: 'jaeger-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/jaeger-exporter/*.json
  #frps类型
  - job_name: 'frps-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/frps-exporter/*.json
  #kube-dns类型
  - job_name: 'kube-dns-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/kube-dns-exporter/*.json
  #kube-proxy类型
  - job_name: 'kube-proxy-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/kube-proxy-exporter/*.json
  #kube-scheduler-exporter类型
  - job_name: 'kube-scheduler-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/kube-scheduler-exporter/*.json
  #kube-state-metrics类型
  - job_name: 'kube-state-metrics-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/kube-state-metrics-exporter/*.json
  #windows-exporter类型
  - job_name: 'windows-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/windows-exporter/*.json