# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
   - rules/*.yml
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    metrics_path: '/metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ "localhost:9090" ]
    #servers
  - job_name: "prometheus-servers"
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/prometheus-servers/*.json
    #spring-boot类型
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/spring-boot-exporter/*.json
  #node-exporter类型
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/node-exporter/*.json
  #nginx-exporter类型
  - job_name: 'nginx-exporter-files'
    metrics_path: '/metrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - config/nginx-exporter/*.json
  #caddy类型
  - job_name: 'caddy-files'
    metrics_path: '/mertrics'
    scrape_interval: 5s
    file_sd_configs:
      - refresh_interval: 5s
        files:
          - /home/prometheus/config/caddy/*.json
