apiVersion: v1
kind: Service
metadata:
  name: coredns-expose
  namespace: kube-system
spec:
  ports:
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
      nodePort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: NodePort
