apiVersion: v1
kind: Service
metadata:
  name: kube-dns-expose
  namespace: kube-system
spec:
  ports:
    - name: http-metrics-dnsmasq
      port: 10054
      protocol: TCP
      targetPort: 10054
      nodePort: 10054
    - name: http-metrics-skydns
      port: 10055
      protocol: TCP
      targetPort: 10055
      nodePort: 10055
  selector:
    k8s-app: kube-dns
  type: NodePort
